openapi: 3.0.0
info:
  title: Truck App API
  version: 1.0.0
paths:
  # Your API paths go here
components:
  schemas:
    OrderResource:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the order.
        pickup_location:
          type: string
          description: The location where the cargo will be picked up.
        delivery_location:
          type: string
          description: The location where the cargo will be delivered.
        cargo_details:
          type: object
          description: Details about the cargo.
          properties:
            weight:
              type: number
              description: The weight of the cargo.
            dimensions:
              type: object
              properties:
                length:
                  type: number
                  description: The length of the cargo.
                width:
                  type: number
                  description: The width of the cargo.
                height:
                  type: number
                  description: The height of the cargo.
        pickup_time:
          type: string
          format: datetime
          description: The time when the cargo will be picked up.
        delivery_time:
          type: string
          format: datetime
          description: The time when the cargo will be delivered.
        status:
          type: string
          description: The current status of the order.
        created_at:
          type: string
          format: datetime
          description: The date and time when the order was created.
        updated_at:
          type: string
          format: datetime
          description: The date and time when the order was last updated.